#!/bin/bash

start-test() {
    KINE_IMAGE=$IMAGE KINE_ENDPOINT="localfs:///tmp/kine-localfs/db" provision-kine
    local kine_url=$(cat $TEST_DIR/kine/*/metadata/url)
    K3S_DATASTORE_ENDPOINT=$kine_url provision-cluster
}
export -f start-test

LABEL=localfs run-test

